on: push
name: php-7.2-validate
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: vtrgomes/github-actions-laravel:7.2

    steps:
    - uses: actions/checkout@v1
    - run: goss --gossfile 7.2/goss.yaml validate
